[project]
name = "research_crew_ollama"
version = "0.1.0"
description = "research_crew_ollama using crewAI"
authors = [{ name = "Kapnobatay", email = "i.dovahkiin@gmail.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.108.0,<1.0.0",
    "flask>=3.0.0,<4.0.0",
    "flask-socketio>=5.3.0"
]

[project.scripts]
research_crew_ollama = "research_crew_ollama.main:run"
run_crew = "research_crew_ollama.main:run"
train = "research_crew_ollama.main:train"
replay = "research_crew_ollama.main:replay"
test = "research_crew_ollama.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
